### ISSUE TITLE
Unable to load procedure when using the file manager plugin

### ISSUE THREAD

**Issue by DylanBruner** [Goldorion/File-Manager-MCreator#4] opened 2021-03-15 23:40 UTC
I installed the file manager plugin and it works great but when I go back to edit a procedure all of the blocks I use are gone I have re-made the procedure a few times and the same thing happens I looked at the java code and it's all there the blocks just are not showing. Is this a bug or am I doing something wrong?

**Comment by Goldorion** [comment] 2021-03-16 00:28
Can you give me your mcreator.log, please? I can't check what is the error without it.

**Comment by MinerMinerMods** [comment] 2021-03-26 21:53
### **I Found a similar problem** 
My MCreator Game Procedure Outputs in the console:
Executing 
    Gradle task: build

Build 
    info: MCreator 2020.5.47520, forge-1.15.2, 64-bit, 7898 MB, Linux, JVM 
    1.8.0_265, JAVA_HOME: /home/_____/Desktop/minecraft/MCreator20205/jdk/jre

> 
    Configure project :

New 
    Dep: net.minecraftforge:forge:1.15.2-31.2.0_mapped_snapshot_20200514-1.15.1

> 
    Task :mcreatorLink UP-TO-DATE

> 
    Task :compileJava FAILED

/home/_____/MCreatorWorkspaces/quantum_warp/src/main/java/net/mcreator/quantumwarp/procedures/LoadModProcedure.java:38: 
    error: illegal start of expression 
 
    .mkdirs();

 
    ^

/home/_____/MCreatorWorkspaces/quantum_warp/src/main/java/net/mcreator/quantumwarp/procedures/LoadModProcedure.java:43: 
    error: ';' expected 
 
      BufferedReader config.jsonReader = new BufferedReader(new 
    FileReader(config.json));

 
                           ^

/home/_____/MCreatorWorkspaces/quantum_warp/src/main/java/net/mcreator/quantumwarp/procedures/LoadModProcedure.java:50: 
    error: ';' expected 
 
     FileWriter config.jsonfw = new FileWriter(config.json);

 
                      ^

/home/_____/MCreatorWorkspaces/quantum_warp/src/main/java/net/mcreator/quantumwarp/procedures/LoadModProcedure.java:64: 
    error: ';' expected 
 
         BufferedReader Config.jsonReader = new BufferedReader(new 
    FileReader(Config.json));

 
                              ^

4 
    errors

FAILURE: 
    Build failed with an exception.

* 
    What went wrong:

Execution 
    failed for task ':compileJava'.

> 
    Compilation failed; see the compiler error output for details.

* 
    Try:

Run 
    with --stacktrace option to get the stack trace. Run with --info or 
    --debug option to get more log output. Run with --scan to get full 
    insights.

* 
    Get more help at https://help.gradle.org

Deprecated 
    Gradle features were used in this build, making it incompatible with 
    Gradle 5.0.

Use 
    '--warning-mode all' to show the individual deprecation warnings.

See 
    https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD 
    FAILED in 5s

1 
    actionable task: 1 executed

BUILD 
    FAILED

Task 
    completed in 120442 milliseconds
And The Popup says that It contains Mod elements that Didn't Compile Properly

-MinerMinerMods

**Comment by MinerMinerMods** [comment] 2021-03-26 21:57
It only Does this with Mod elements From File_Manager 
Also Here is the code in the procedure`package net.mcreator.quantumwarp.procedures;

import net.minecraft.world.IWorld;
import net.minecraft.client.Minecraft;

import net.mcreator.quantumwarp.QuantumWarpModVariables;
import net.mcreator.quantumwarp.QuantumWarpModElements;

import java.util.Map;

import java.io.IOException;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.File;
import java.io.BufferedReader;

import com.google.gson.JsonObject;
import com.google.gson.GsonBuilder;
import com.google.gson.Gson;

import com.electronwill.nightconfig.core.Config;

@QuantumWarpModElements.ModElement.Tag
public class LoadModProcedure extends QuantumWarpModElements.ModElement {
	public LoadModProcedure(QuantumWarpModElements instance) {
		super(instance, 93);
	}

	public static void executeProcedure(Map<String, Object> dependencies){
		if(dependencies.get("world") == null) {
			if(!dependencies.containsKey("world"))
				System.err.println("Failed to load dependency world for procedure LoadMod!");
			return;
		}
				IWorld world = (IWorld) dependencies.get("world");
		File   = new File(Minecraft.getInstance().gameDir, File.separator + "config.json");
 .mkdirs();
{
	config.jsonbw.write((("Configuration file ")+""+(Minecraft.getInstance().gameDir)+""+("  Thank you for downloading my mod")));
	config.jsonbw.newLine();
}try {
	BufferedReader config.jsonReader = new BufferedReader(new FileReader(config.json));
	String stringiterator = "";
	while((stringiterator = config.jsonReader.readLine()) != null) {
		Gson gson = new GsonBuilder().setPrettyPrinting().create();
JsonObject obj = new JsonObject();
obj.addProperty("DevCmds", (false));obj.addProperty("Snapshot", (false));
try {
  FileWriter config.jsonfw = new FileWriter(config.json);
  config.jsonfw.write(gson.toJson(obj));
  config.jsonfw.close();
} catch (IOException exception) {
  exception.printStackTrace();
}
	}
	config.jsonReader.close();
} catch (FileNotFoundException e) {
	e.printStackTrace();
} catch (IOException e) {
    e.printStackTrace();
}{
	try {
		BufferedReader Config.jsonReader = new BufferedReader(new FileReader(Config.json));
		String json = "";
	String line = "";
		while((line = Config.jsonReader.readLine()) != null) {
			json = json + line;
		}
		Config.jsonReader.close();
	JsonObject obj = new Gson().fromJson(json, JsonObject.class);
	        QuantumWarpModVariables.WorldVariables.get(world).Dev_Cmds =(boolean)obj.get("DevCmds").getAsBoolean();
        QuantumWarpModVariables.WorldVariables.get(world).syncData(world);
        QuantumWarpModVariables.WorldVariables.get(world).Snapshot =(boolean)obj.get("Snapshot").getAsBoolean();
        QuantumWarpModVariables.WorldVariables.get(world).syncData(world);
  
	} catch (FileNotFoundException e) {
		e.printStackTrace();
	} catch (IOException e) {
		e.printStackTrace();
	}
}
	}
}
` 
I hope you can Fix this.
Good Luck

**Comment by MinerMinerMods** [comment] 2021-03-27 01:24
> Can you give me your mcreator.log, please? I can't check what is the error without it.

Basically he means give me the information in your console except sensitive info

**Comment by Goldorion** [comment] 2021-03-27 01:29
> 
> 
> > Can you give me your mcreator.log, please? I can't check what is the error without it.
> 
> Basically he means give me the information in your console except sensitive info

No, I want the mcreator.log, not the console.

**Comment by Goldorion** [comment] 2021-04-18 04:25
I'm not able to reproduce this bug. It may be fixed in one of the last commits I made.

**Closed by Goldorion** 2021-04-18 04:25 UTC
