### ISSUE TITLE
file_variable.java.ftl in 1.16.5 doesn't use the new procedure block code causing a code generation error.

### ISSUE THREAD

**Issue by Rinnray** [Goldorion/File-Manager-MCreator#22] opened 2021-12-17 23:49 UTC
I like how you showed in the pictures and it wasn't working. MCreator seem to not think there is a procedure whenever those blocks are in it. Cause no dependencies shows up in triggers on i.e blocks. There's nothing in the console showing it.
So I started to read the comments and some issues here as well and I'm not the only one that seems to be having this, nor is there any fixes either.
After reading what you wrote [here](https://github.com/Goldorion/File-Manager-MCreator/issues/21#issuecomment-995796508) I gave it a shot and made a new workspace for forge 1.16.5. But nothing. The procedure made wont even show up in lists of procedures in triggers. 
![image](https://user-images.githubusercontent.com/47090855/146620124-9f7c9142-417d-40ce-98d4-046c481629df.png)
![image](https://user-images.githubusercontent.com/47090855/146620223-95b63c6a-cdea-404a-be9e-2c7f2738c6a5.png)

**Comment by Goldorion** [comment] 2021-12-18 00:07
Stupid question. Did you save your procedure before trying to select it?

**Comment by Rinnray** [comment] 2021-12-18 00:07
xD Of course. Multiple times in fact just to be sure. Also closed the item and re-opened it cause I know being on the trigger page and saving a procedure it doesn't instantly show up.

**Comment by Goldorion** [comment] 2021-12-18 00:08
Because before accusing someone, have real proof. I tested the example and other users such as NorthWestTrees also tested the new version and everyone nobody had a problem.

**Comment by Rinnray** [comment] 2021-12-18 00:13
????? How am I accusing someone? How is this a closed issue, invalid and "working as designed"?
That's all I can show as I'm not shown anything; as there's nothing in console about it, otherwise I would have tried to fix it myself and not write here to a stuck up dev that seems to not be able to accept criticism or having open issues.

**Comment by Goldorion** [comment] 2021-12-18 00:21
> 

When you just say something doesn't work when testing something I tested myself and you don't provide details such as the mcreator.log and a minimal reproducible workspace, it's a valid reason to close the issue in my opinion. Stop saying I don't accept criticism. If you explain yourself correctly explaining your POV with good arguments, I'm glad to receive criticisms. Simply, currently, this is not the case. If you don't know how to report a bug, this is not my fault. I can't do something about this, but if you report a potential with everything you can show or give, now this is a problem I'm glad to receive. So as long as I don't have something to use, this is an issue will be kept closed.

**Comment by Rinnray** [comment] 2021-12-18 00:45
"Working for me" and "working for a couple of others" aren't good arguments to bring up if you're gonna talk about good or bad arguments. Cause looking at some other issues here that seems to be the same, I'm not exactly alone with this.
I have people messaging me about problems they're having with my things that I know work for me and some others. But instead of being stuck up about it, I ask follow up questions to get what I need then I look into what I can.
If it turns out to just be an end user issue, then I calmly let them know what they're doing wrong and help them in the right direction.

Everyone reports bugs differently and everyone wants to have it reported differently. If **you** can't provide a concrete way of how **you** want to receive issues then that's not my fault. Since I can't know what you want to receive as proof.
I explained my POV from the information I was holding. Me not being given anything more from MCreator isn't exactly my doing either.
If you're keen on helping or getting more information about an issue or criticism.
Instead of replying with snarky and passive aggressive replies, just simply and calmly explain what you need or want to be shown (since you don't have it written down somewhere); and since you don't have any wiki or faq or whatever about potential issues, then it's not the end users fault for having to open up an issue either. People can't read minds.

If helping end users with any issues, no matter how stupid and irritated it is, if it's so much effort, then having some kind of knowledge base is going to get that load of your shoulder. Then people can read through that as well if there's anything happening to them.

Now, if mcreator.log and workspace is what you need then I'll gladly try and get that for you. But really not sure going this way of having to get the correct information is the right one. But you do you.

**Comment by Goldorion** [comment] 2021-12-18 02:46
> "Working for me" and "working for a couple of others" aren't good arguments

I never said that too...

> Everyone reports bugs differently and everyone wants to have them reported differently.

But a good bug report is always the same. You provide all information you can provide to have a quick fix/answer. This is what you didn't do. You said "I have a problem. Your example does not work. You do not even test your things. Please fix it." and you put 2 pictures. Ok, one of the pictures shows the procedure itself, but this procedure is something I verified and it works. Where are logs, exact steps to reproduce it, a workspace with the problem?

> If you can't provide a concrete way of how you want to receive issues then that's not my fault.

I admit I should provide a bug report template, but first, you are MCreator, so it can't change a lot compared to the bug reports for MCreator. There are also minimal things you need to provide when you report a bug about something.

> I explained my POV from the information I was holding.

No, you didn't. Read previous points. If you don't know something this is ok, but this is the right time to learn.

> passive aggressive replies, just simply and calmly explain what you need or want to be shown

I'm not aggressive. I just want to explain something to you.

> since you don't have any wiki

Video(s) should come soon (from NWT) and the current wiki is the example on the plugin's page.

> then having some kind of knowledge base is going to get that load of your shoulder. 

This is exactly the purpose of the two example pictures and the demo workspace.

> But really not sure going this way of having to get the correct information is the right one.

Giving logs and a minimal reproducible workspace are the best things you can give for a bug report concerning MCreator. Logs write everything that happens in MCreator, including errors and the workspace allows me (or another contributor in the case of a bug about MCreator) to show the bug in action and don't have to mess with everything to try to reproduce it. 

> But you do you.

https://github.com/MCreator/MCreator/issues/new?assignees=&labels=bug&template=bug_report.yml
https://sifterapp.com/blog/2012/08/tips-for-effectively-reporting-bugs-and-issues/
https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
Not alone to want this, I think.

**Comment by Rinnray** [comment] 2021-12-18 03:57
> You provide all information you can provide to have a quick fix/answer. This is what you didn't do.
Exactly **can** provide. I wrote what I could which, I know; isn't much or til help. But that's literally all I had; there wasn't anything in console, I've had a look through MCreator folders and there's no logs that I can find unless they're somewhere different.

There were no crashes no nothing. If I had more I obviously would have given that as well.

> Where are logs, exact steps to reproduce it, a workspace with the problem?

Didn't have anything and I'll provide a workspace below.

> There are also minimal things you need to provide when you report a bug about something.

I'm aware, but like stated above. That's all I had.

> No, you didn't. Read previous points. If you don't know something this is ok

Pretty sure I don't have to repeat myself again; but if I didn't know something I would have already asked.

> Video(s) should come soon (from NWT)

Yea I'm waiting for that but configs got outvoted by something else so it'll be a bit lmao.

> Giving logs and a minimal reproducible workspace are the best things you can give for a bug report concerning MCreator.

>Not alone to want this, I think.

No that last part was just a misunderstanding, and I could have probably worded it better; which I apologize for if that is the case. What I meant with:
> But really not sure going this way of having to get the correct information is the right one. But you do you.

Is that, me having to question you closing the ticket and adding those tags shouldn't be a route that has to be taken for me to get useful info to be able to give you what you need/want to be able to help. It is a two way street after all.


Unless there's more that needs to be cleared; I'm honestly ready to move on lmao.


Like I stated above, I've looked through the MCreator folders that I can find. But I'm unable to find the "mcreator.log" you mentioned.
I would assume it was in `.mcreator/logs` but that folder is empty. Then the only other log folder I was able to find is just the logs that also shows in MCreator (and all other Minecraft instances; which at the time. Didn't give me anything to give you).

I had already deleted the test Workspace but threw one back together and basically, still not working.
I can't show this so you're just gonna see for yourself when you get the workspace. But the procedure only shows up in the triggers dropdown if this block isn't connected:
![image](https://user-images.githubusercontent.com/47090855/146627667-064e8717-77b4-493f-975b-4e916b323ffa.png)
The "Generated code viewer" also becomes red and shows no changes.

Here's the workspace: 
[filemanagertest.zip](https://github.com/Goldorion/File-Manager-MCreator/files/7738687/filemanagertest.zip)
I think all the needed files for it is there at least. Do let me know otherwise.

**Comment by northwesttreesgaming** [comment] 2021-12-18 04:08
> The "Generated code viewer" also becomes red and shows no changes.

I have not tested it again but I had the plugin in the workspace plugin folder not the .MCreator plugin folder and I did have the same issue with this block @Goldorion I did tell you about this on discord.

Maybe confirm that you have your plugin in the user profile .mcreator folders plugin and you have removed all older versions of the mod. If it still causes problems then it for sure is a issue, and for some reason the workspace he sent me worked for some bazar reason.

**Comment by Rinnray** [comment] 2021-12-18 04:12
> folder not the .MCreator plugin folder
I'm running Linux so I haven't installed MCreator the usual way. So I've been placing the plugins in the "MCreator20213" folder that I unzip when downloading the program.
So I have not tried to place it in the .MCreator folder, but I'll give that a shot as well.

**Comment by Goldorion** [comment] 2021-12-18 04:13
> Didn't have anything

mcreator.logis not the console. This is an external file located at Users/yourUser/.mcreator/logs.

> But I'm unable to find the "mcreator.log" you mentioned.

If you are in the right folder, it's impossible to not be able to see it.

**Comment by Rinnray** [comment] 2021-12-18 04:13
> > Didn't have anything
> 
> mcreator.logis not the console. This is an external file located at Users/yourUser/.mcreator/logs.
> 
> > But I'm unable to find the "mcreator.log" you mentioned.
> 
> If you are in the right folder, it's impossible to not be able to see it.

Looked in there and it's empty. Don't know what else to tell you.

**Comment by Goldorion** [comment] 2021-12-18 04:15
> But the procedure only shows up in the triggers dropdown if this block isn't connected:

I re-tested after my previous comment (the long one) and @northwesttreesgaming can confirm it worked fine with the example workspace I gave.

**Comment by Rinnray** [comment] 2021-12-18 04:16
> with the example workspace I gave.

The one you gave sure. But no one should have to constantly grab that to get things to work as expected. Am I wrong?

**Comment by Goldorion** [comment] 2021-12-18 04:16
> > > Didn't have anything
> > 
> > 
> > mcreator.logis not the console. This is an external file located at Users/yourUser/.mcreator/logs.
> > > But I'm unable to find the "mcreator.log" you mentioned.
> > 
> > 
> > If you are in the right folder, it's impossible to not be able to see it.
> 
> Looked in there and it's empty. Don't know what else to tell you.

Put a screenshot of the folder (including the path (no need to see your name)) because if you really have nothing, it's something you should report on the MCreator's repo.

**Comment by Goldorion** [comment] 2021-12-18 04:17
> > with the example workspace I gave.
> 
> The one you gave sure. But no one should have to constantly grab that to get things to work as expected. Am I wrong?

This is the same thing as screenshots used as examples.

**Comment by Rinnray** [comment] 2021-12-18 04:21
> > > with the example workspace I gave.
> > 
> > 
> > The one you gave sure. But no one should have to constantly grab that to get things to work as expected. Am I wrong?
> 
> This is the same thing as screenshots used as examples.

![image](https://user-images.githubusercontent.com/47090855/146628698-beb5a61b-753a-4171-a913-f6c17042e684.png)
There's the picture of the folder.

>  and I did have the same issue with this block Goldorion I did tell you about this on discord.

Not sure if you missed, but North seems like he did also have the same issue I'm having with this one block.

**Comment by Rinnray** [comment] 2021-12-18 04:21
> > > with the example workspace I gave.
> > 
> > 
> > The one you gave sure. But no one should have to constantly grab that to get things to work as expected. Am I wrong?
> 
> This is the same thing as screenshots used as examples.

![image](https://user-images.githubusercontent.com/47090855/146628698-beb5a61b-753a-4171-a913-f6c17042e684.png)
There's the picture of the folder.

>  and I did have the same issue with this block Goldorion I did tell you about this on discord.

Not sure if you missed, but North seems like he did also have the same issue I'm having with this one block.

**Comment by Goldorion** [comment] 2021-12-18 04:25
![image](https://user-images.githubusercontent.com/38427877/146628766-b7ac96ae-3a3d-4a73-a8ed-8b6011b45c65.png)

Simply to show you both procedures work fine and they both use the set block.
(missing dependency is due to a GUI specific dependency)

**Comment by Goldorion** [comment] 2021-12-18 04:29
> > > > with the example workspace I gave.
> > > 
> > > 
> > > The one you gave sure. But no one should have to constantly grab that to get things to work as expected. Am I wrong?
> > 
> > 
> > This is the same thing as screenshots used as examples.
> 
> ![image](https://user-images.githubusercontent.com/47090855/146628698-beb5a61b-753a-4171-a913-f6c17042e684.png) There's the picture of the folder.
> 
> > and I did have the same issue with this block Goldorion I did tell you about this on discord.
> 
> Not sure if you missed, but North seems like he did also have the same issue I'm having with this one block.

Try to re-install MCreator because logs work fine on my side.

**Comment by Rinnray** [comment] 2021-12-18 04:39
> ![image](https://user-images.githubusercontent.com/38427877/146628766-b7ac96ae-3a3d-4a73-a8ed-8b6011b45c65.png)
> 
> Simply to show you both procedures work fine and they both use the set block. (missing dependency is due to a GUI specific dependency)

I'm not doubting that it's working for you. I.. I don't know what else to write about that, honestly. To me it feels like you're just trying to avoid that there is *something* going on. Specially when North even came in and said he *did* have the same issue that he talked to you about; and others in these issues had them as well. But you've kept going back to "It works for me".

> Try to re-install MCreator because logs work fine on my side.

There isn't much for me to re-install since it comes pre-packaged for Linux Users.
But I nuked everything related to MCreator *just in case* and here ya go, I managed to dig logs up.

By first saving the procedure without that one block that breaks it. Then added it and saved it, now I found a log after running find in my terminal.
[mcreator.log](https://github.com/Goldorion/File-Manager-MCreator/files/7738731/mcreator.log)

**Comment by Goldorion** [comment] 2021-12-18 04:44
> To me it feels like you're just trying to avoid that there is something going on.

No, I'm just trying to understand the problem when MCreator downloads the new Forge version on my laptop, so I can test with yours.


And asI said earlier, the mcreator.log gave me all info I needed.

**Comment by Goldorion** [comment] 2021-12-18 04:50
I found the cause. Both of us were right on what we were saying. It worked for me because I tested on Forge 1.17.1 and then, I pasted the files in other generators, but for a reason, the file used by the block (the output block giving values to the setter) still had some old FTL code causing a code generation error.

I don't know what happened with your MCreator, but simply giving the mcreator.log can solve most of this error type. I will fix this bug tomorrow and release a patch after. During this time, you can still use Forge 1.17.1 and it will work fine.

**Comment by Rinnray** [comment] 2021-12-18 04:52
Not sure if GIFs work so I'll just
*insert Steve Harvey "Thank you Jesus" GIF*

I'll just wait for the patch then, making a mod for 1.16.5 for modpack so unable to use another version.

**Closed** 2021-12-18 06:17 UTC
Labels: bug

**Comment by Goldorion** [comment] 2021-12-18 06:25
@Rinnray I just released a patch version fixing this bug. You should be able to use it perfectly now. Next time you report a bug, fill in the bug report template and everything will be good. ;)
